AWSTemplateFormatVersion: 2010-09-09
Parameters:
  ImageId:
    Description: Image ID for the EC2 instance.
    Type: String
  KeyName:
    Description: Name of an EC2 KeyPair to enable SSH access to the instance.
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  SSHLocation:
    Description: 'The IP address range that can be used to access the web server using SSH.'
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
Resources:
  VPC1:
    Type: 'AWS::EC2::VPC'
    Properties:
      Tags:
        - Key: 'Name'
          Value: 'VPC1'
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      CidrBlock: '10.1.0.0/16'
  PublicSubnet1a:
    Type: 'AWS::EC2::Subnet'
    Properties:
      Tags:
        - Key: 'Name'
          Value: 'PublicSubnet1a'
      VpcId: !Ref VPC1
      AvailabilityZone: 'us-east-1a'
      CidrBlock: '10.1.1.0/24'
      MapPublicIpOnLaunch: 'true'
  PrivateSubnet1a:
    Type: 'AWS::EC2::Subnet'
    Properties:
      Tags:
        - Key: 'Name'
          Value: 'PrivateSubnet1a'
      VpcId: !Ref VPC1
      AvailabilityZone: 'us-east-1a'
      CidrBlock: '10.1.2.0/24'
      MapPublicIpOnLaunch: 'false'
  PublicSubnet1b:
    Type: 'AWS::EC2::Subnet'
    Properties:
      Tags:
        - Key: 'Name'
          Value: 'PublicSubnet1b'
      VpcId: !Ref VPC1
      AvailabilityZone: 'us-east-1b'
      CidrBlock: '10.1.3.0/24'
      MapPublicIpOnLaunch: 'true'
  PrivateSubnet1b:
    Type: 'AWS::EC2::Subnet'
    Properties:
      Tags:
        - Key: 'Name'
          Value: 'PrivateSubnet1b'
      VpcId: !Ref VPC1
      AvailabilityZone: 'us-east-1b'
      CidrBlock: '10.1.4.0/24'
      MapPublicIpOnLaunch: 'false'
  InternetGateway1:
    Type: 'AWS::EC2::InternetGateway'
  VPCGatewayAttachment1:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      InternetGatewayId: !Ref InternetGateway1
      VpcId: !Ref VPC1
  PublicRouteTable1:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref VPC1
  PublicRoute1:
    Type: 'AWS::EC2::Route'
    Properties:
      DestinationCidrBlock: '0.0.0.0/0'
      RouteTableId: !Ref PublicRouteTable1
      GatewayId: !Ref InternetGateway1
  PublicSubnetRouteTableAssociation1a:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      RouteTableId: !Ref PublicRouteTable1
      SubnetId: !Ref PublicSubnet1a
  PublicSubnetRouteTableAssociation1b:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      RouteTableId: !Ref PublicRouteTable1
      SubnetId: !Ref PublicSubnet1b
  JumpInstanceSecurityGroup1:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      VpcId: !Ref VPC1
      GroupDescription: Allow access  SSH traffic
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: !Ref SSHLocation
  JumpInstance1a:
    Type: 'AWS::EC2::Instance'
    Properties:
      Tags:
        - Key: 'Name'
          Value: 'JumpInstance1a'
      InstanceType: 't2.small'
      ImageId: !Ref ImageId
      KeyName: !Ref KeyName
      NetworkInterfaces:
        - GroupSet:
            - !Ref JumpInstanceSecurityGroup1
          AssociatePublicIpAddress: 'true'
          DeviceIndex: '0'
          DeleteOnTermination: 'true'
          SubnetId: !Ref PublicSubnet1a
  JumpInstance1b:
    Type: 'AWS::EC2::Instance'
    Properties:
      Tags:
        - Key: 'Name'
          Value: 'JumpInstance1b'
      InstanceType: 't2.small'
      ImageId: !Ref ImageId
      KeyName: !Ref KeyName
      NetworkInterfaces:
        - GroupSet:
            - !Ref JumpInstanceSecurityGroup1
          AssociatePublicIpAddress: 'true'
          DeviceIndex: '0'
          DeleteOnTermination: 'true'
          SubnetId: !Ref PublicSubnet1b
  PrivateInstanceSecurityGroup1:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      VpcId: !Ref VPC1
      GroupDescription: Allow access  SSH traffic
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          Description: 'Allow SSH access from jump servers'
          SourceSecurityGroupId: !Ref JumpInstanceSecurityGroup1
  PrivateInstance1a:
    Type: 'AWS::EC2::Instance'
    Properties:
      Tags:
        - Key: 'Name'
          Value: 'PrivateInstance1a'
      InstanceType: 't2.small'
      ImageId: !Ref ImageId
      KeyName: !Ref KeyName
      NetworkInterfaces:
        - GroupSet:
            - !Ref PrivateInstanceSecurityGroup1
          AssociatePublicIpAddress: 'false'
          DeviceIndex: '0'
          DeleteOnTermination: 'true'
          SubnetId: !Ref PrivateSubnet1a
  PrivateInstance1b:
    Type: 'AWS::EC2::Instance'
    Properties:
      Tags:
        - Key: 'Name'
          Value: 'PrivateInstance1b'
      InstanceType: 't2.small'
      ImageId: !Ref ImageId
      KeyName: !Ref KeyName
      NetworkInterfaces:
        - GroupSet:
            - !Ref PrivateInstanceSecurityGroup1
          AssociatePublicIpAddress: 'false'
          DeviceIndex: '0'
          DeleteOnTermination: 'true'
          SubnetId: !Ref PrivateSubnet1b
